### ISSUE TITLE
./testing_utils.py:34:22: F821 undefined name 'pu'

### ISSUE THREAD

**Issue by cclauss** [flomlo/ntm_keras#1]
flake8 testing of https://github.com/flomlo/ntm_keras

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./testing_utils.py:34:22: F821 undefined name 'pu'
        import pudb; pu.db
                     ^
```
https://github.com/flomlo/ntm_keras/blob/master/testing_utils.py#L34

**Comment by flomlo** [comment]
This is the standard(?) way to call the pudb debugger, which is here only called in case testing runs into NaN.

I dont think this is an issue.
