### ISSUE TITLE
return_sequences=False

### ISSUE THREAD

**Issue by shanest** [flomlo/ntm_keras#6]
Hi,
I'm trying to use your NTM implementation to do sequence classification.  Footnote 1 of your PDF says that `return_sequences=False` is broken.  But is this still true?  By setting that parameter, I am getting tensors of the right shape, i.e. `[batch_size, output_size]` with no time dimension.  

Performance is not great yet, but I want to make sure that's due to finnicky hyper-parameters and not something still being broken with `return_sequences`.  

Thanks!

**Comment by flomlo** [comment]
Hello!

The PDF refers to the branch https://github.com/flomlo/ntm_keras/tree/SemDL, which is frozen and nowadays several dozens commits behind. The whole PDF was for an assignemt for some seminar in my university and will no longer be updated (I should probably document that somewhere).

As for the `return_sequences=False`-problem: Yes, I think I fixed that at some point. I can remember faintly being annoyed by it myself some time ago as I wanted to use it myself for sequences.

With the bug still in place the code crashed turing compile time with some unambiguous errors, so if it doesnt, I fixed it.


Performance can be quite a hassle indeed. If you ever use it successfully on some non-trivial problem please tell me about it :)


Best,

oml
